apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: fastapi-kubernetes-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fastapi-kubernetes
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50